# Generated by Django 3.1.5 on 2021-01-30 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_category_expanse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expanse',
            name='category',
        ),
        migrations.AlterField(
            model_name='expanse',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expanses', to='budget.project'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
